---

### Generic smell configuration

detectors:
  IrresponsibleModule:
    enabled: false
  UncommunicativeModuleName:
    enabled: false
  TooManyStatements:
    max_statements: 10

# https://github.com/troessner/reek/blob/master/README.md#working-with-rails
directories:
  "app/controllers":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
    TooManyInstanceVariables:
      max_instance_variables: 20
    TooManyMethods:
      max_methods: 30
  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/mailers":
    InstanceVariableAssumption:
      enabled: false
    TooManyInstanceVariables:
      enabled: false
  "app/models":
    InstanceVariableAssumption:
      enabled: false
  "app/jobs":
    UtilityFunction:
      enabled: false
  "app/channels":
    UtilityFunction:
      enabled: false
  "app/validators":
    UtilityFunction:
      enabled: false
  "app/services":
    UtilityFunction:
      enabled: false
    FeatureEnvy:
      enabled: false

exclude_paths:
  - db/
